config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#top'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'users/index', to: 'users/registrations#index'
    get 'users/destroy', to: 'users/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get 'home/about'

  resource :account, only: %i[show edit update] do
    member do
      get :bookmarks
    end
  end

  resources :patients do
    resource :bookmarks, only: %i[create destroy]
    resources :additional_comments, only: %i[create destroy]

    collection do
      get :search
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :set_q
  before_action :set_user

  def top; end

  def about; end

  def search
    @results = @q.result.order(created_at: :desc).page(params[:page]).per(5)
  end

  private

  def set_q
    @q = Patient.ransack(params[:q])
  end

  def set_user
    @user = current_user
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/about.html.erb
<div class="about-main">
  <h2 class="about-title">カルテメモアプリとは</h2>
  <div class="purpose">
    <p>紙カルテに記入する時間、</p>
    <p>電話をいただいた際紙カルテを探す手間を省くため、</p>
    <p>１クリックで職種関係なく情報共有できるよう</p>
    <p>仕事の効率化と診察記録を残すアプリです。</p>
    <p>簡単に患者名入れるだけで検索ができます。</p>
  </div>

  <div class="recommendation">
    <h2 class="none">オススメの使い方</h2>
    <p>朝一ログインした状態にしておく</p>
    <p>予約時注意が必要な患者はbookmarkしておくと<br>
    一覧で閲覧できるようになっているため便利です。</p>
  </div>

  <div class="form-home">
    <p><%= link_to "ホームへ戻る", root_path %></p>
  </div>
</div>

app/views/home/top.html.erb
<div class="home_view">
  <h1 class= "title">患者情報メモアプリ</h1>
  <div class="link_container">
    <p><span>＼</span><%= link_to "患者登録はこちらをクリック", new_patient_path %><span>／</span></p>
    <p><%= link_to "要注意患者一覧", bookmarks_account_path, class:"link_p" %></p>
    <p><%= link_to "患者一覧", patients_path, class:"link_p" %></p>
  </div>
  <div class="top_head">
    <div class="top_search_page">
      <div class = "search_content">
        <h1 class= "title">患者検索</h1>
        <%= search_form_for @q, url: search_patients_path do |f| %>
          <%= f.label :medical_record_number_eq , 'カルテ番号', class:"search_column"%>
          <%= f.search_field :medical_record_number_eq, class:"search_window" %>
          <br>
          <%= f.label :name_cont, '名前', class:"search_column2" %>
          <%= f.search_field :name_cont, class:"search_window" %>
          <br>
          <%= f.label :phone_number_eq, '電話番号', class:"search_column3" %>
          <%= f.search_field :phone_number_eq, class:"search_window" %>
          <%= f.submit 'search', class:"search_btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>