config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#top'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'users/index', to: 'users/registrations#index'
    get 'users/destroy', to: 'users/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get 'home/about'

  resource :account, only: %i[show edit update] do
    member do
      get :bookmarks
    end
  end

  resources :patients do
    resource :bookmarks, only: %i[create destroy]
    resources :additional_comments, only: %i[create destroy]

    collection do
      get :search
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
# frozen_string_literal: true

class Patient < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarkd_users, through: :bookmarks, source: :user
  has_many :additional_comments, dependent: :destroy

  with_options presence: true do
    validates :name, length: { maximum: 10 }
    validates :warn
    validates :phone_number
    validates :medical_record_number
    validates :maintenance_or_treatment
    validates :visit_date
  end

  validate :day_after_today, on: :create

  def day_after_today
    errors[:base] << '今日を含む過去の日付を入力して下さい' if !visit_date.nil? && (visit_date > Date.today)
  end
end

app/controllers/patients_controller.rb
# frozen_string_literal: true

class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_q
  before_action :set_user
  before_action :set_patient, only: %i[show edit update destroy]

  def index
    @patients = Patient.order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(params.require(:patient).permit(:name, :warn, :phone_number, :medical_record_number, :maintenance_or_treatment, :visit_date))
    @patient.user_id = current_user.id
    if @patient.save
      redirect_to :patients
      flash[:notice] = '登録が完了しました'
    else
      render 'new'
    end
  end

  def show
    @bookmark = Bookmark.new
    @additional_comments = @patient.additional_comments
    @additional_comment = AdditionalComment.new
  end

  def edit; end

  def update
    if @patient.update(patient_params)
      flash[:notice] = '患者情報を更新しました'
      redirect_to :patients
    else
      render 'edit'
    end
  end

  def destroy
    @patient.destroy
    flash[:notice] = '患者登録を削除'
    redirect_to :patients
  end

  def search
    @results = @q.result.order(created_at: :desc).page(params[:page]).per(5)
  end

  private

  def set_q
    @q = Patient.ransack(params[:q])
  end

  def patient_params
    params.require(:patient).permit(:name, :warn, :phone_number, :medical_record_number, :maintenance_or_treatment, :visit_date)
  end

  def set_user
    @user = current_user
  end

  def set_patient
    @patient = Patient.find(params[:id])
  end
end

app/views/patients/_form.html.erb
<%= form_with model: patient do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
  <div class="register">
    <div>
      <%= f.label :medical_record_number, "カルテ番号", class:"label_name" %><br>
      <%= f.text_field :medical_record_number, autofocus: true, autocomplete: "number", placeholder:"number",class:"patient_pass" %>
    </div>

    <div>
      <%= f.label :name, "名前", class:"label_name" %><br>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder:"name",class:"patient_pass" %>
    </div>

    <div>
      <%= f.label :phone_number, "電話番号", class:"label_name" %><br />
      <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number", placeholder:"phone_number",class:"patient_pass" %>
    </div>

    <div>
      <%= f.label :warn, "注意すること", class:"label_name" %><br />
      <%= f.text_area :warn, autofocus: true, autocomplete: "warn", class:"patient_pass" %>
    </div>

    <div>
      <%= f.label :radio_button, "治療内容", class:"label_name" %><br />
      <%= f.radio_button :maintenance_or_treatment, "メンテ中"%>メンテ中 or <%= f.radio_button :maintenance_or_treatment, "治療中", checked: true %>治療中
    </div>

    <div>
      <%= f.label :visit_date, "来院日" %><br>
      <%= f.date_field :visit_date %>
    </div>

    <div class="patient_submit">
      <p><%= f.submit "登録する", class:"button" %></p>
    </div>

    <div class="form-home">
      <p><%= link_to "ホームへ戻る", root_path %></p>
    </div>
  </div>
<% end %>

app/views/patients/edit.html.erb
<div class="patient_view">
  <h2 class="title">患者詳細編集</h2>
  <%= render "form", patient: @patient %>
</div>

app/views/patients/index.html.erb
<div class="patient_list">
  <h3 class="patient_h3">患者検索</h3>
  <%= search_form_for @q, url: search_patients_path do |f| %>
    <%= f.label :medical_record_number_eq , 'カルテ番号', class:"search_column"%>
    <%= f.search_field :medical_record_number_eq, class:"search_window" %>
    <br>
    <%= f.label :name_cont, '名前', class:"search_column2" %>
    <%= f.search_field :name_cont %>
    <br>
    <%= f.label :phone_number_eq, '電話番号', class:"search_column3" %>
    <%= f.search_field :phone_number_eq %>
    <%= f.submit 'search', class:"search_btn" %>
  <% end %>
  <h3 class="patient_h3">登録者一覧</h3>
  <table class="table_list">
    <thead>
      <tr class="tr_list">
        <th class="th_list">カルテ番号</th>
        <th class="th_list">名前</th>
        <th class="th_list">電話番号</th>
        <th class="th_list">注意すること</th>
        <th class="th_list">治療内容</th>
        <th class="th_list">来院日</th>
        <th class="th_list">詳細</th>
        <th class="th_list">編集</th>
        <th class="th_list">削除</th>
      </tr>
    </thead>

    <tbody>
      <% @patients.each do |patient| %>
        <tr class="tr_list">
          <td class="td_list"><%= patient.medical_record_number %></td>
          <td class="td_list"><%= patient.name %></td>
          <td class="td_list"><%= patient.phone_number %></td>
          <td class="td_list"><%= patient.warn %></td>
          <td class="td_list"><%= patient.maintenance_or_treatment %></td>
          <td class="td_list"><%= patient.visit_date %></td>
          <td class="td_list"><%= link_to "詳細", patient %></td>
          <td class="td_list"><%= link_to "編集", edit_patient_path(patient.id) %></td>
          <td class="td_list"><%= link_to "削除", patient, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @patients %> 
  <div class="form-home">
    <p><%= link_to "ホームへ戻る", root_path %></p>
  </div>
</div>

app/views/patients/new.html.erb
<div class="patient_view">
  <h2 class="title">患者登録</h2>
  <%= render "form", patient: @patient %>
</div>

app/views/patients/search.html.erb
<div class="patient_list">
  <h3 class="patient_h3">検索結果</h3>
    <table class="table_list">
      <thead>
        <tr class="tr_list">
          <th class="th_list">カルテ番号</th>
          <th class="th_list">名前</th>
          <th class="th_list">電話番号</th>
          <th class="th_list">注意すること</th>
          <th class="th_list">治療内容</th>
          <th class="th_list">来院日</th>
          <th class="th_list">詳細</th>
          <th class="th_list">編集</th>
          <th class="th_list">削除</th>
        </tr>
      </thead>

      <tbody>
        <% @results.each do |patient| %>
          <tr class="tr_list">
            <td class="td_list"><%= patient.medical_record_number %></td>
            <td class="td_list"><%= patient.name %></td>
            <td class="td_list"><%= patient.phone_number %></td>
            <td class="td_list"><%= patient.warn %></td>
            <td class="td_list"><%= patient.maintenance_or_treatment %></td>
            <td class="td_list"><%= patient.visit_date %></td>
            <td class="td_list"><%= link_to "詳細", patient %></td>
            <td class="td_list"><%= link_to "編集", edit_patient_path(patient.id) %></td>
            <td class="td_list"><%= link_to "削除", patient, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @results %> 

    <div class="form-home">
      <p><%= link_to "ホームへ戻る", root_path %></p>
    </div>
</div>

app/views/patients/show.html.erb
<div class="patient_show">
  <p> <%= alert %> </p>
  <h2 class="patient_h3">患者情報詳細</h2>
  <table class="table_list">
    <tbody>
      <tr class="tr_list">
        <th class="th_list">カルテ番号</th>
        <td class="td_list"><%= @patient.medical_record_number %></td>
      </tr>

      <tr class="tr_list">
        <th class="th_list">名前</th>
        <td class="td_list"><%= @patient.name %></td>
      </tr>

      <tr class="tr_list">
        <th class="th_list">電話番号</th>
        <td class="td_list"><%= @patient.phone_number %></td>
      </tr>

      <tr class="tr_list">
        <th class="th_list">注意すること</th>
        <td class="td_list"><%= @patient.warn %></td>
      </tr>

      <tr class="tr_list">
        <th class="th_list">治療内容</th>
        <td class="td_list"><%= @patient.maintenance_or_treatment %></td>
      </tr>

      <tr class="tr_list">
        <th class="th_list">来院日</th>
        <td class="td_list"><%= @patient.visit_date %></td>
      </tr>

      <h3><span>＼</span> ※注意が必要な場合push! <span>／</span></h3>


      <% if current_user. already_bookmarkd?(@patient) %>
        <%= button_to 'ブックマーク取り消す', patient_bookmarks_path(@patient), method: :delete %>
      <% else %>
        <%= button_to 'ブックマークする', patient_bookmarks_path(@patient) %>
      <% end %>
    </tbody>
  </table>

  <h3 class="comment_h3">追加コメント</h3>
  <% @additional_comments.each do |additional_comment| %>
    <div>
      <%= additional_comment.user.username %>
      <%= additional_comment.content %>
      <%= additional_comment.posted_date %>
      <%= link_to '削除',  patient_additional_comment_path(@patient, additional_comment), method: :delete, class: "comment_delete" %>
    </div>
  <% end %>

  <%= form_for [@patient, @additional_comment] do |f| %>
    <%= f.text_field :content %><br>
    <%= f.label :visit_date, "来院日", class:"visit_date" %><br>
    <%= f.date_field :posted_date %>
    <%= f.submit '追加メモする' %>
  <% end %>

  <div class="show_submit">
    <p><%= link_to"患者登録一覧に戻る", :patients %></p>
    <p><%= link_to "編集する", edit_patient_path(@patient.id) %></p>
    <p><%= link_to "削除する", @patient, method: :delete, data: { confirm: "本当に削除しますか？" } %></p>
  </div>
</div>