config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#top'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'users/index', to: 'users/registrations#index'
    get 'users/destroy', to: 'users/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get 'home/about'

  resource :account, only: %i[show edit update] do
    member do
      get :bookmarks
    end
  end

  resources :patients do
    resource :bookmarks, only: %i[create destroy]
    resources :additional_comments, only: %i[create destroy]

    collection do
      get :search
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
   <div class="alert alert-warning">
      <%= model.errors.full_messages.last %>
   </div>
 <% end %>

app/views/layouts/_footer.html.erb
   <footer>
     <p class="footer_memo">© 2022 patient.</p>
   </footer>

app/views/layouts/_header.html.erb
<header>
  <div class="header">
  <div class="header__inner">
    <% if @current_user %>
      <%= link_to "患者メモアプリ", root_path(@current_user) %>
    <% else %>
      <h1>患者メモアプリ</h1>
    <% end %>
    <div class="header__navgroup">
      <% if @user.email == 'guest@test.com' %>
        <div class="header__navitem"><%= link_to "-about-", home_about_path %></div>
        <div class="header__navitem"><%= link_to "myアカウント" , account_path %></div>
        <div class="header__navitem"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></div>
      <% elsif user_signed_in? %>
        <div class="header__navitem"><%= link_to "-about-", home_about_path %></div>
        <div class="header__navitem"><%= link_to "myアカウント" , account_path %></div>
        <div class="header__navitem"><%= link_to "アカウント編集" , edit_account_path %></div>
        <div class="header__navitem"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></div>
      <% else %>
        <div class="header__navitem"><%= link_to "ログイン", "/users/sign_in" %></div>
        <div class="header__navitem"><%= link_to "新規登録", "/users/sign_up" %></div>
      <% end %>
    </div>
  </div>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PatientMemoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag    'application' %>
    <!-- コード追加 Bootstrap CSS読み込みコード-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- コード追加 Bootstrap JavaScript読み込みコード-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
  <%if flash.notice%>
      <p class="notice"><%= notice %></p>
    <%end%>
    <%if flash.alert%>
      <p class="alert"><%= alert %></p>
    <%end%>

    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>