config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#top'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'users/index', to: 'users/registrations#index'
    get 'users/destroy', to: 'users/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get 'home/about'

  resource :account, only: %i[show edit update] do
    member do
      get :bookmarks
    end
  end

  resources :patients do
    resource :bookmarks, only: %i[create destroy]
    resources :additional_comments, only: %i[create destroy]

    collection do
      get :search
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  before_action :set_user

  def show; end

  def edit; end

  def update
    if (params[:user][:password] == params[:user][:password_confirmation]) &&
       @user.update(account_params)
      flash[:notice] = "#{@user.username}の情報を更新しました"
      redirect_to root_path(@user)
    else
      render :edit
    end
  end

  def bookmarks
    bookmarks = Bookmark.where(user_id: @user.id).pluck(:patient_id)
    @bookmark_lists = Patient.find(bookmarks)
    @patients = Patient.order(created_at: :desc).page(params[:page]).per(5)
  end

  private

  def account_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = current_user
  end
end

app/views/accounts/bookmarks.html.erb
<div class="patient_list">
  <h3 class="patient_h3">ブックマーク一覧</h3>
  <table class="table_list">
    <thead>
      <tr class="tr_list">
        <th class="th_list">カルテ番号</th>
        <th class="th_list">名前</th>
        <th class="th_list">電話番号</th>
        <th class="th_list">注意すること</th>
        <th class="th_list">治療内容</th>
        <th class="th_list">来院日</th>
        <th class="th_list">詳細</th>
      </tr>
    </thead>

    <tbody>
      <% @bookmark_lists.each do |patient| %>
        <tr class="tr_list">
          <td class="td_list"><%= patient.medical_record_number %></td>
          <td class="td_list"><%= patient.name %></td>
          <td class="td_list"><%= patient.phone_number %></td>
          <td class="td_list"><%= patient.warn %></td>
          <td class="td_list"><%= patient.maintenance_or_treatment %></td>
          <td class="td_list"><%= patient.visit_date %></td>
          <td class="td_list"><%= link_to "詳細", patient %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @patients %> 


  <div class="form-home">
    <p><%= link_to "ホームへ戻る", root_path %></p>
  </div>
</div>

app/views/accounts/edit.html.erb
<div class="account_view">
  <h2 class="title">アカウント編集</h2>
  <%= form_with model: @user, url: account_path do |f| %>
    <%= render "devise/shared/error_messages", resource: @user %>
    <div class="register">
      <div>
        <%= f.label :username, "アカウント名" %><br>
        <%= f.text_field :username, autofocus: true, autocomplete: "account",placeholder:"account",class:"edit_pass" %>
      </div>

      <div>
        <%= f.label :email, "メールアドレス" %><br>
        <%= f.email_field :email, autofocus: true, autocomplete: "email",placeholder:"email",class:"edit_pass" %>
      </div>

      <div>
        <%= f.label :password, "新しいパスワード" %><br />
        <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %>文字以上に設定してください)</em><br />
        <% end %>
        <%= f.password_field :password, autofocus: true, autocomplete: "new-password",  class: "edit_pass" %>
      </div>

      <div>
        <%= f.label :password_confirmation, "新しいパスワードの確認" %><br />
        <%= f.password_field :password_confirmation, autocomplete: "new-password",  class: "edit_pass" %>
      </div>

      <div class="edit_submit">
        <p><%= f.submit "更新", class:"button" %></p>
      </div>

      <div class="form-home">
        <p><%= link_to "ホームへ戻る", root_path %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/accounts/show.html.erb
<div class="account_view">
  <h2 class="title">アカウント詳細</h2>
    <table>
      <tr>
        <th class="table_header">名前</th>
        <td><%= @user.username %></td>
      </tr>

      <tr>
        <th class="table_header">メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>
    </table>

    <div class="link">
      <%= link_to "ブックマーク一覧",  bookmarks_account_path,class:"bookmark_list"  %>
      <br>
      <%= link_to "編集" , edit_account_path, class:"edit_account" %>
    </div>

    <div class="form-home">
      <p><%= link_to "ホームへ戻る", root_path %></p>
    </div>
</div>